### ISSUE TITLE
Request documentation of CA bundle for self-signed cert.

### ISSUE THREAD

**Issue by QWERTY92009** [PaloAltoNetworks/pcs-toolbox#15]
## Documentation link

https://github.com/PaloAltoNetworks/pcs-toolbox

## Describe the problem

When configuring as described, the resulting config file does not have a CA bundle. The connection attempt appears to start, but there is an error that the server cert was rejected. 

## Suggested fix

Maybe there is a way to not check the server cert, e.g., like curl -k.

**Comment by tkishel** [comment]
Specifying a CA bundle is optional.

Please provide a sample configuration file, with credentials redacted, and the resulting error message.

You can set ca_bundle to 'False' and that will disable ssl verification (not recommended).

**Comment by QWERTY92009** [comment]
Thanks. Setting ca_bundle to "False" seems to have worked, but now I'm getting an ldap error. I'll attach the redacted config file. The resulting error is: 

```
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,


Status Code: 401
API (https://twistlock-dev.s2e2dev.viasat.io/api/v1/authenticate) responded with an error
{"err":"invalid ldap credentials"}
```
[pc-settings-redacted.conf.txt](https://github.com/PaloAltoNetworks/pcs-toolbox/files/7841352/pc-settings-redacted.conf.txt)

**Comment by tkishel** [comment]
You can disable that warning with `export PYTHONWARNINGS="ignore:Unverified HTTPS request"` but again disabling that is not recommended. 

I have pushed changes to the configuration code so that `ca_bundle` does not have to be specified (and should not be specified) if it is not necessary, so please pull down the latest code and delete the `ca_bundle` key from your configuration file (and the preceding comma if it was the last key to maintain valid JSON).

The LDAP error is unrelated to this issue or the code itself, as it appears to be coming from your IDP. If you are using Self-Hosted/On-Premise Compute, that provider will be defined in Manage > Authentication > Identity. You will need to verify your credentials and review the logs in your Console (Manage > Logs > History) and/or LDAP provider.

**Comment by QWERTY92009** [comment]
Thanks @tkishel. This all looks good. However, our IDP requires MFA. Is there any way to use a token instead?

**Comment by QWERTY92009** [comment]
Thanks @tkishel. That seems to work fine!

**Comment by tkishel** [comment]
Cool!
